# Generated by Django 4.1.4 on 2022-12-23 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('ap_id', models.AutoField(primary_key=True, serialize=False)),
                ('bssid', models.CharField(blank=True, max_length=500, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=500, null=True)),
                ('range_start', models.IntegerField(blank=True, null=True)),
                ('range_end', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_id', models.AutoField(primary_key=True, serialize=False)),
                ('building_name', models.CharField(blank=True, max_length=500, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('loc_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rssi_value', models.IntegerField(blank=True, null=True)),
                ('ap_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.accesspoint')),
            ],
        ),
        migrations.AddField(
            model_name='accesspoint',
            name='building_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.building'),
        ),
    ]
