# Generated by Django 4.1.4 on 2023-02-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="far_from_ap",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
