# Generated by Django 4.1.4 on 2023-02-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_location_far_from_ap"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="far_from_ap",
            new_name="far_from_ap_m",
        ),
        migrations.RenameField(
            model_name="location",
            old_name="rssi_value",
            new_name="range_end",
        ),
        migrations.RemoveField(
            model_name="accesspoint",
            name="range_end",
        ),
        migrations.RemoveField(
            model_name="accesspoint",
            name="range_start",
        ),
        migrations.AddField(
            model_name="location",
            name="range_start",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
