# Generated by Django 4.1.4 on 2023-02-12 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_far_from_ap_location_far_from_ap_m_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accesspoint",
            old_name="bssid",
            new_name="ssid",
        ),
    ]
